name: AI Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  ai-review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install requests python-dotenv

      - name: Create .env (GitHub version)
        run: |
          echo "OLLAMA_URL=${{ secrets.OLLAMA_URL }}" >> .env
          echo "OLLAMA_MODEL=${{ secrets.OLLAMA_MODEL }}" >> .env
          echo "AI_REVIEW_MAX_DIFF_CHARS=2000" >> .env
          echo "AI_REVIEW_TIMEOUT_SECONDS=300" >> .env
          echo "AI_REVIEW_STRICT=1" >> .env

      - name: Run AI Reviewer
        run: python ci/run_ai_checks.py
